apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config

data:
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}