apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: jenkins-agent-role

rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  - services
  - configmaps
  - secrets
  - namespaces
  - serviceaccounts
  - ingresses
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete

- apiGroups:
  - apps
  - networking.k8s.io
  resources:
  - deployments
  - statefulsets
  - ingresses
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - update
  - delete

- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create