replicaCount: 1

image:
  repository: mysql
  tag: "8.0"
  pullPolicy: IfNotPresent

service:
  port: 3306

config:
  database: devopsdb

secret:
  rootPassword: Root@123

persistence:
  size: 5Gi

resources:
  requests:
    cpu: 200m
    memory: 256Mi

  limits:
    cpu: 500m
    memory: 512Mi