apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql

spec:
  serviceName: mysql-service

  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mysql

  template:
    metadata:
      labels:
        app: mysql

    spec:
      containers:
      - name: mysql

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.port }}

        envFrom:
        - configMapRef:
            name: mysql-config

        - secretRef:
            name: mysql-secret

        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql

        resources:
          {{- toYaml .Values.resources | nindent 10 }}

  volumeClaimTemplates:
  - metadata:
      name: mysql-storage

    spec:
      accessModes:
      - ReadWriteOnce

      resources:
        requests:
          storage: {{ .Values.persistence.size }}