apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-gateway

spec:
  replicas: 2

  selector:
    matchLabels:
      app: api-gateway

  template:
    metadata:
      labels:
        app: api-gateway

    spec:
      containers:
      - name: api-gateway

        image: techwithdiwana/api-gateway:v3

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 3000

        envFrom:
        - configMapRef:
            name: api-gateway-config

        - secretRef:
            name: api-gateway-secret

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "256Mi"

        readinessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 5
          periodSeconds: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 3000

          initialDelaySeconds: 15
          periodSeconds: 20