name: Hello Workflow

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: echo "Hello GitHub Actions"